"""add last_date for chat

Revision ID: 68f74f7e1c60
Revises: d55e7a9ad1a7
Create Date: 2025-05-08 13:04:21.461305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68f74f7e1c60'
down_revision: Union[str, None] = 'd55e7a9ad1a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('last_date', sa.DateTime(), nullable=True))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'notifications', 'users', ['creator'], ['username'])
    op.drop_column('chats', 'last_date')
    # ### end Alembic commands ###
