"""ret

Revision ID: d55e7a9ad1a7
Revises: e0de9033b6f0
Create Date: 2025-05-07 23:46:14.041956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd55e7a9ad1a7'
down_revision: Union[str, None] = 'e0de9033b6f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('chats', 'encryption_key')
    # alembic upgrade headop.add_column('messages', sa.Column('content', sa.String()))
    # op.drop_column('messages', 'encrypted_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'notifications', 'users', ['creator'], ['username'])
    op.add_column('messages', sa.Column('encrypted_content', sa.BLOB(), nullable=False))
    op.drop_column('messages', 'content')
    op.add_column('chats', sa.Column('encryption_key', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###
