"""encrypt for chats

Revision ID: e0de9033b6f0
Revises: 
Create Date: 2025-05-07 16:39:26.297181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0de9033b6f0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('encryption_key', sa.LargeBinary(), nullable=False))
    op.drop_column('users', 'encryption_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('encryption_key', sa.BLOB(), nullable=False))
    op.drop_column('chats', 'encryption_key')
    # ### end Alembic commands ###
